config/routes.rb
# Add your custom routes here.  If in config/routes.rb you would 
# add <tt>map.resources</tt>, here you would add just <tt>resources</tt>

# resources :tog_users
                                                                            
resources :users
resource  :session

login    '/login',    :controller => 'sessions', :action => 'new'
logout   '/logout',   :controller => 'sessions', :action => 'destroy'
signup   '/signup',   :controller => 'users',    :action => 'new'
forgot   '/forgot',   :controller => 'users',    :action => 'forgot'
denied   '/denied',   :controller => 'authorization',    :action => 'denied'
reset    '/reset/:reset_code',          :controller => 'users', :action => 'reset'
activate '/activate/:activation_code',  :controller => 'users', :action => 'activate'
resend_activation '/resend_activation', :controller => 'users', :action => 'resend_activation'

namespace(:admin) do |admin| 
  admin.resources :users
end

namespace(:member) do |member|
  member.with_options(:controller => 'users') do |user|
    user.my_account       '/account',         :action => 'my_account'
    user.destroy_account  '/destroy',         :action => 'destroy'
    user.change_password  '/change_password', :action => 'change_password', :conditions => { :method => :post }
  end
end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  include Authentication
  include Authentication::ByPassword
  include Authentication::ByCookieToken
  include Authorization::AasmRoles
  
    validates_presence_of     :login, 
      :unless => :email_as_login?
    validates_length_of       :login, 
      :within => 3..40, :unless => :email_as_login?
    validates_uniqueness_of   :login, 
      :unless => :email_as_login?
    validates_format_of       :login, 
      :with => Authentication.login_regex, :message => Authentication.bad_login_message, :unless => :email_as_login?
  

  validates_presence_of     :email
  validates_length_of       :email,    :within => 6..100 #r@a.wk
  validates_uniqueness_of   :email
  validates_format_of       :email,    :with => Authentication.email_regex, :message => Authentication.bad_email_message

  named_scope :admin, :conditions => {:admin => true}
  named_scope :active, :conditions => {:state => 'active'}
  
  has_many :comments

  after_create :send_activation_request
  after_save :send_activation_or_reset_mail


  # HACK HACK HACK -- how to do attr_accessible from here?
  # prevents a user from submitting a crafted form that bypasses activation
  # anything else you want your user to change should be added here.
  attr_accessible :login, :email, :password, :password_confirmation



  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  #
  # uff.  this is really an authorization, not authentication routine.  
  # We really need a Dispatch Chain here or something.
  # This will also let us return a human error message.
  #
  def self.authenticate(login, password)
    if Tog::Config["plugins.tog_user.email_as_login"]
      login_column = :email
    else
      login_column = :login
    end
    u = find_in_state :first, :active, :conditions => { login_column => login} # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end  

  def login=(value)
    write_attribute :login, (value ? value.downcase : nil)
  end

  def email=(value)
    write_attribute :email, (value ? value.downcase : nil)
  end

  def forgot_password
    @forgotten_password = true
    self.make_password_reset_code
  end

  def reset_password
    # First update the password_reset_code before setting the
    # reset_password flag to avoid duplicate email notifications.
    update_attribute(:password_reset_code, nil)
    @reset_password = true
  end
  
  #used in mailer
  def recently_forgot_password?
    @forgotten_password
  end

  def recently_reset_password?
    @reset_password
  end
  
  #HACK. Needed by tog_mail, which includes a filter for crating default folders after activation
  def recently_activated?
    @activated
  end

  protected
    
    def make_activation_code
        self.deleted_at = nil
        self.activation_code = self.class.make_token
    end
    
    def make_password_reset_code
      self.password_reset_code = Digest::SHA1.hexdigest( Time.now.to_s.split(//).sort_by {rand}.join )
      save(false)
    end    
    
    def send_activation_request
      UserMailer.deliver_signup_notification(self)
    end

    def send_activation_or_reset_mail
      UserMailer.deliver_activation(self) if self.recently_activated?
      Activity.report(self, :activate, self) if self.recently_activated?
      UserMailer.deliver_reset_notification(self) if self.recently_forgot_password?       
    end

    def email_as_login?
     Tog::Config["plugins.tog_user.email_as_login"]
    end

end


  # validates_presence_of     :login, :message => I18n.t("tog_user.model.login_required")
  # validates_presence_of     :email, :message => I18n.t("tog_user.model.email_required")
  # validates_presence_of     :password,                   :if => :password_required?, :message => I18n.t("tog_user.model.password_required")
  # validates_presence_of     :password_confirmation,      :if => :password_required?
  # validates_length_of       :password, :within => 4..40, :if => :password_required?
  # validates_confirmation_of :password,                   :if => :password_required?, :message => I18n.t("tog_user.model.password_mismatch")
  # validates_length_of       :login,    :within => 3..40, :message => I18n.t("tog_user.model.login_to_short")
  # validates_length_of       :email,    :within => 3..100
  # validates_uniqueness_of   :login, :case_sensitive => false, :message => I18n.t("tog_user.model.login_in_use")
  # validates_uniqueness_of   :email, :case_sensitive => false, :message => I18n.t("tog_user.model.email_in_use")

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController        

  before_filter :find_user, :except => :index
  
  
  def index
    @order_by = params[:order_by] || "login"
    @sort_order = params[:sort_order] || "asc"
    @page = params[:page] || '1'
    
    condition = ""
    conditions_values = Hash.new
    
    if params[:search_term]
      conditions_values[:search_term] = "%#{params[:search_term]}%"
      condition = "(login like :search_term or email like :search_term)"
    end
    
    if params[:age]
      condition += " and " if condition != ""
      today = Date.today
      conditions_values[:aged] = {
        :today => today,
        :week => today - 7.days,
        :month => today - 1.month,
      }[params[:age].to_sym]
      condition += "(created_at > :aged)"
    end
    
    if params[:state]
      condition += " and " if condition != ""
      conditions_values[:state] = params[:state]
      condition += "(state = :state)"
    end    
    
    @users = User.find(:all, :order => "#{@order_by} #{@sort_order}",
                             :conditions => [condition, conditions_values]
                      ).paginate :page => @page,
                                 :per_page => Tog::Config['plugins.tog_core.pagination_size']
  end

  def new       
    @user = User.new(params[:user])
  end

  def create
    @user = User.new(params[:user])
    @user.make_activation_code
    @user.save!
    redirect_to(admin_users_url)
    flash[:ok] = I18n.t("tog_user.admin.user_created", :login => @user.login)
  rescue ActiveRecord::RecordInvalid
    flash[:error] = @title = I18n.t("tog_user.admin.error_saving")
    render :action => 'new'
  end

  def update
    @user.send(%{#{params[:state_event]}!}) unless params[:state_event].blank?
    @user.admin = params[:user][:admin]
    @user.update_attributes!(params[:user])
    redirect_to(admin_users_url)
    flash[:ok] = I18n.t("tog_user.admin.user_updated", :login => @user.login)
  rescue ActiveRecord::RecordInvalid
    flash[:error] = I18n.t("tog_user.admin.error_saving")
    render :action => 'edit'
  end

  protected

  def find_user
    @user = User.find(params[:id]) if params[:id]
  end

end

app/controllers/member/users_controller.rb
class Member::UsersController < Member::BaseController        

  before_filter :find_user

  def change_password
    return unless request.post?
    if User.authenticate(current_user.login, params[:old_password])
      if (params[:password] == params[:password_confirmation])
        current_user.password_confirmation = params[:password_confirmation]
        current_user.password = params[:password]
        if current_user.save
          flash[:ok] = I18n.t("tog_user.member.password.changed")
        else
          flash[:error] = I18n.t("tog_user.member.password.not_changed")
        end
      else
        flash[:error] = I18n.t("tog_user.member.password.mismatch")
        @old_password = params[:old_password]
      end
    else
      flash[:error] = I18n.t("tog_user.member.password.invalid")
    end
    redirect_to :action => 'my_account'
  end
  
  def destroy
    current_user.destroy
    cookies.delete :auth_token
    reset_session
    flash[:ok] = I18n.t("tog_user.member.account.removed")
    redirect_back_or_default('/')
  end

  protected

    def find_user
      @user = current_user
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "sessions"

  def create
    # cookies.delete :auth_token
    # protects against session fixation attacks, wreaks havoc with 
    # request forgery protection.
    # uncomment at your own risk
    # reset_session
    @user = User.new(params[:user])
    @user.login ||= @user.email if Tog::Config["plugins.tog_user.email_as_login"]
    
    captcha_validated = Tog::Config["plugins.tog_user.captcha_enabled"] ? verify_recaptcha(@user) : true
    
    # If there is no users yet, set the first one to admin.
    @user.admin = User.find(:all).blank?
    
    @user.register! if captcha_validated && @user.valid?
    if @user.errors.empty?
      redirect_back_or_default(Tog::Config["plugins.tog_user.default_redirect_on_signup"])
      flash[:notice] = I18n.t("tog_user.user.sign_up")
    else
      render :action => 'new'
    end
  end
  
  def resend_activation
    if current_user
      UserMailer.deliver_signup_notification(current_user)
      flash[:notice] = I18n.t("tog_user.user.activation_resent")
    end
    redirect_to root_path
  end
  
  def activate
    self.current_user = params[:activation_code].blank? ? false : User.find_by_activation_code(params[:activation_code])
    case
      when (!params[:activation_code].blank?) && logged_in? && !current_user.active?
        current_user.activate!
        flash[:notice] = I18n.t("tog_user.user.sign_up_completed")
        redirect_back_or_default(Tog::Config["plugins.tog_user.default_redirect_on_activation"])
      when params[:activation_code].blank?
        flash[:error] = I18n.t("tog_user.user.activate_code_missing")
        redirect_back_or_default('/')
      else
        flash[:error] = I18n.t("tog_user.user.activation_code_bogus")
        redirect_back_or_default('/')
    end
  end

  def forgot
    if request.post?
      if @user = User.find_by_email(params[:user][:email])
        @user.forgot_password
        flash[:notice] = I18n.t("tog_user.user.password_reset_sent", :email => @user.email)
      else
        flash[:error] = I18n.t("tog_user.user.password_reset_not_found", :email => params[:user][:email])
      end
      redirect_back_or_default(Tog::Config["plugins.tog_user.default_redirect_on_forgot"])
    end
  end
  
  def reset
    @user = User.find_by_password_reset_code(params[:reset_code]) unless params[:reset_code].nil?
    if request.post?
      if @user.update_attributes(:password => params[:user][:password], :password_confirmation => params[:user][:password_confirmation])
        @user.reset_password
        self.current_user = @user
        flash[:ok] = I18n.t("tog_user.user.password_updated", :email => @user.email)
        redirect_back_or_default(Tog::Config["plugins.tog_user.default_redirect_on_reset"])
      else
        render :action => :reset
      end
    end
  end

end

app/helpers/admin/user_helper.rb
module Admin
  module UserHelper
    
    def select_state_tag(user)
      default_state = user.new_record? ? :passive : user.aasm_current_state

      events  = user.aasm_events_for_current_state.collect do |x| 
        [ I18n.t("tog_user.model.states.actions.#{x}"), x ] 
      end

      options = events.insert(0, [ "", '' ])

      select_tag("state_event", options_for_select(options.uniq, default_state))
    end
        
    # Return link to sort column with toggled sort order
    def link_to_sortable_column_header(field, order_by, sort_order, name)
      if order_by == field.to_s
        sort_order = (sort_order || '').upcase == 'DESC' ? 'ASC' : 'DESC'
        arrow = (sort_order == 'ASC') ? 'down' : 'up' 
      else
        sort_order = 'ASC'
        arrow = nil
      end
      new_params = params.merge(:order_by => field.to_s, :sort_order => sort_order)
      html = link_to(name, new_params)
      html << image_tag("/tog_core/images/ico/arrow-#{arrow}.gif") if arrow
      html
    end
  
 
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/_form.html.erb
<table class="tableE">
  <caption><%= I18n.t("tog_user.admin.login_details") %></caption>
  <tbody>
  <tr>
      <th scope="row"><%=I18n.t("tog_user.model.name")%></th>
      <td nowrap="nowrap"><%=f.text_field :login, :class=>"fieldbox" %></td>
  </tr>
  <tr>
      <th scope="row"><%=I18n.t("tog_user.model.password")%></th>
      <td nowrap="nowrap"><%= f.password_field :password, :class=>"fieldbox" %></td>
  </tr>
  <tr>
      <th scope="row"><%=I18n.t("tog_user.model.password_confirmation")%></th>
      <td nowrap="nowrap">
        <%= f.password_field :password_confirmation, :class=>"fieldbox" %>
        <br />
        <span class="helpinfo"><%=I18n.t("tog_user.model.change_password_explanation")%></span>
      </td>
  </tr>
  <tr>
      <th scope="row"></th>
      <td nowrap="nowrap">
        <%= f.check_box :admin %> <%=I18n.t("tog_user.model.admin_user")%>
      </td>
  </tr>
</tbody></table>
<table class="tableE">
  <caption><%= I18n.t("tog_user.admin.personal_details") %></caption>
  <tbody>
  <tr>
      <th scope="row"><%=I18n.t("tog_user.model.email")%></th>
      <td nowrap="nowrap"><%= f.text_field :email, :class=>"fieldbox" %></td>
  </tr>
  <tr>
      <th scope="row"><%=I18n.t("tog_user.model.state")%></th>
      <td nowrap="nowrap">
        <strong class="highlight"><%= I18n.t("tog_user.model.states.#{@user.aasm_current_state}") %></strong>
        <br/>
        <%= I18n.t("tog_user.admin.change") %>:
        <%= select_state_tag(@user) %>
      </td>
  </tr>
</tbody></table>

app/views/admin/users/edit.html.erb
<h1><%= link_to I18n.t("tog_user.plugin_title"), admin_users_path%> / <%= @user.login %></h1>

<br />

<%= error_messages_for :user %>
<% form_for :user, :url => admin_user_path(@user), :html => {:id => "edit_user", :method => :put} do |f| -%>
  <%= render :partial => 'form', :locals => { :f => f } %>

  <br />

  <div class="actions">
    <%= submit_tag I18n.t("tog_user.admin.update"), {:accesskey => "s", :class=>"button"} %>
  </div>

<% end -%>

app/views/admin/users/index.html.erb
<h1><%= I18n.t("tog_user.plugin_title") %></h1>

<p><%= link_to I18n.t("tog_user.admin.create_user"),  new_admin_user_url, {:class => "button add", :title => I18n.t("tog_user.admin.create_user")} %></p>

<table class="tableE">
  <thead>
    <tr>
      <% [:login, :email, :state, :created_at].each do |field| %>
        <th scope="col">
          <%= link_to_sortable_column_header(field, @order_by, @sort_order,
                I18n.t("tog_user.model.#{field}")) %>
        </th>
      <% end %>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td colspan="4" class="info_results">
        <span class="info_items"><%= page_entries_info @users %></span>
        <span class="pages_navigation right">
          <%= will_paginate @users, :container => false %>
        </span>
        </td>
    </tr>
  </tfoot>
  <tbody>
    <% @users.each do |user| %>
    <tr<%= cycle(' class="pair"','') -%>>
      <td><strong><%= link_to user.login, edit_admin_user_url(user), {:title => I18n.t("tog_user.admin.edit_user")} -%></strong></td>
      <td nowrap="nowrap"><%= mail_to user.email, user.email, {:title => I18n.t("tog_user.admin.send_email")} -%></td>
      <td><%= I18n.t("tog_user.model.states.#{user.aasm_current_state}") %></td>
      <td nowrap="nowrap"><%= I18n.l(user.created_at, :format => :long) -%></td>
    </tr>
    <% end %>
  </tbody>
</table>

<% content_for :sidebar do %>
  <div id="portlet_search_user" class="portlet portletD">
    <h2>
      <span>
        <%= I18n.t("tog_user.admin.search_user") %>... 
      </span>
    </h2>
    <div class="portlet_content">
      <% form_tag(admin_users_path, :method => :get) do %>
        <%= text_field_tag :search_term, params[:search_term], :size => 22 %>
        <%= submit_tag " > " %>
      <% end %>      
      <small>
        <%= I18n.t("tog_user.admin.search_user_info") %>
      </small>
    </div>    
  </div>

  <br/> 
  <div class="portlet portletE" id="portlet_userFilter">
    <h2>
      <span>
        <%= I18n.t("tog_user.admin.filter_users") %>
      </span>
    </h2>
    <div class="portlet_content">
      <ul>
        <li>
          <ul>
            <li><%= link_to I18n.t("tog_user.admin.filter_all"), admin_users_path(:search_term => params[:search_term])%></li>
          </ul>
        </li>
        <li>
          <%= I18n.t("tog_user.admin.age_filter") %>
          <ul>
            <% [:today, :week, :month].each do |age| %>
              <%= filter_item(:age, age, I18n.t("tog_user.admin.age_filter_fields.#{age}")) %> 
            <% end %>
          </ul>
        </li>
        <li>
          <%= I18n.t("tog_user.admin.user_state_filter") %>
          <ul>
            <% [:passive, :pending, :active, :suspended, :deleted].each do |state| %>
              <%= filter_item(:state, state, I18n.t("tog_user.admin.user_state_filter_fields.#{state}")) %>
            <% end %>
          </ul>        
        </li>
      </ul>
    </div>    
  </div> 
  <br/>  
<% end %>

app/views/admin/users/new.html.erb
<h1><%= link_to I18n.t("tog_user.plugin_title"), admin_users_path%> / <%= I18n.t("tog_user.admin.create_account") %></h1>

<br />

<%= error_messages_for :user %>
<% form_for :user, :url => admin_users_path,  :html => {:id => "settings"} do |f| -%>

  <%= render :partial => 'form', :locals => { :f => f } %>

  <br />

  <div class="actions">
    <%= submit_tag I18n.t("tog_user.admin.create"), {:accesskey => "s", :class=>"button"} %>
  </div>

<% end -%>